### ISSUE TITLE
App keeps crashing

### ISSUE THREAD

**Issue by Tim-Brass** [athombv/nl.action#12]
For some reason the app (2.1.2) keeps crashing...

Homey 0.10.7

Error: signal_not_registered
at Function.<anonymous> (/opt/homey-client/system/manager/ManagerMicrocontroller/ManagerMicrocontroller.js:232:23)
at App._onMessage (/opt/homey-client/system/lib/App.js:443:22)
at emitTwo (events.js:87:13)
at ChildProcess.emit (events.js:172:7)
at internal/child_process.js:696:12
at nextTickCallbackWith0Args (node.js:420:9)
at process._tickCallback (node.js:349:13)

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please let me know if you still encounter this issue with the [latest stable version](https://firmware.athom.com/).

Thank you!
